# Generated by Django 2.2.5 on 2019-09-14 12:19
from datetime import datetime

from django.db import migrations, models


def set_new_expriration_date(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Menu = apps.get_model('menu', 'Menu')
    for menu in Menu.objects.all():
        if menu.expiration_date is not None:
            try:
                menu.new_expiration_date = datetime.strptime(str(menu.expiration_date), '%Y-%m-%d %H:%M:%S.%f').date()
            except ValueError:
                menu.new_expiration_date = datetime.strptime(str(menu.expiration_date), '%Y-%m-%d %H:%M:%S').date()
            menu.save()

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='new_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(set_new_expriration_date),
    ]
