# Generated by Django 2.2.5 on 2019-09-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_new_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='expiration_date',
        ),
    ]
