# Generated by Django 2.2.5 on 2019-11-24 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0003_remove_menu_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='new_expiration_date',
            new_name='expiration_date',
        ),
    ]
